In [1]:
# 사전 리스트
import pandas as pd
df_hawkish = pd.read_csv('df_hawkish_dict_ver4.csv')
df_dovish = pd.read_csv('df_dovish_dict_ver4.csv')
dic_hawkish = list(df_hawkish['ngram'])
dic_dovish = list(df_dovish['ngram'])

In [2]:
from tqdm.notebook import tqdm

In [3]:
import pandas as pd 
import numpy as np
import re

In [4]:
df_dic = pd.read_csv('ver1_ngramized_minutes_test.csv')#n_gram 만든 라벨링된 의사록
df_dic

,Unnamed: 0,ID,date,sent,n_gram
0,0,2005년도 제10차,2005-05-12,['일부 위원은 내외금리차 역전에 따라 자금의 해외유출이 대규모로 발생될 가능성을 ...,"['내외/NNG', '금리갭/NNG', '역전/NNG', '자금/NNG', '해외/..."
1,1,2005년도 제10차,2005-05-12,"', '이에 대해 관련부서에서는 우리나라에서는 그러한 사례가 없었기 때문에 대만과 ...","['대해/VV', '그러/NNG', '사례/NNG', '없/VA', '사례/NNG'..."
2,2,2005년도 제10차,2005-05-12,"', '동 위원은 자금의 해외유출에 대한 정책적 대응을 위해 내외금리나 환율에 대해...","['자금/NNG', '해외/NNG', '유출/NNG', '정책/NNG', '대응/N..."
3,3,2005년도 제10차,2005-05-12,"', '다른 일부 위원은 최근 금융기관의 외화대출이 늘어나고 있는 것과 관련하 여 ...","['금융기관/NNG', '외화대출/NNG', '늘/VV', '금융기관/NNG', '..."
4,4,2005년도 제10차,2005-05-12,"', '또 다른 일부 위원은 전년 동기와 비교할 때 금년 1～4월중 국내시장에 대 ...","['또/MAG', '비교/NNG', '하/VV', '때/NNG', '중/NNG', ..."
...,...,...,...,...,...
10151,10151,2017년도 제7차,2017-04-13,"', '외환시장의 효율성 제고를 위해서는 중장기적으로 원화를 국제화하고 경제주체들 ...","['외환시장/NNG', '효율성/NNG', '제고/NNG', '위하/VV', '중장..."
10152,10152,2017년도 제7차,2017-04-13,"', '또한 동 위원은 비은행 가계대출이 증가세 관리와 같은 대응이 요구될 정도 의...","['비은행/NNG', '가계/NNG', '대출/NNG', '증가/NNG', '관리/..."
10153,10153,2017년도 제7차,2017-04-13,"', '앞으로는 개별 기관별로도 파악해 볼 수 있도록 입수자료를 좀 더 미시 화하는...","['기관/NNG', '파악/NNG', '있/VV', '입수/NNG', '자료/NNG..."
10154,10154,2017년도 제7차,2017-04-13,"', '이에 대해 관련부서에서는 작년에 은행의 여신심사 강화 등으로 가계대출수 요가...","['대해/VV', '은행/NNG', '여신/NNG', '심사/NNG', '강화/NN..."
10155,10155,2017년도 제7차,2017-04-13,"', '아울러 동 위원은 우리나라의 수익률곡선이 다른 나라에 비해 평탄화되어 있 다...","['아울러/MAG', '일드커브/NNG', '나라/NNG', '비해/VV', '플래..."

In [5]:
#-------------------------------필요없는 컬럼 제거하기=---------------------------------
df_dic = df_dic[['ID', 'date', 'sent', 'n_gram']]

In [6]:
df_dic

,ID,date,sent,n_gram
0,2005년도 제10차,2005-05-12,['일부 위원은 내외금리차 역전에 따라 자금의 해외유출이 대규모로 발생될 가능성을 ...,"['내외/NNG', '금리갭/NNG', '역전/NNG', '자금/NNG', '해외/..."
1,2005년도 제10차,2005-05-12,"', '이에 대해 관련부서에서는 우리나라에서는 그러한 사례가 없었기 때문에 대만과 ...","['대해/VV', '그러/NNG', '사례/NNG', '없/VA', '사례/NNG'..."
2,2005년도 제10차,2005-05-12,"', '동 위원은 자금의 해외유출에 대한 정책적 대응을 위해 내외금리나 환율에 대해...","['자금/NNG', '해외/NNG', '유출/NNG', '정책/NNG', '대응/N..."
3,2005년도 제10차,2005-05-12,"', '다른 일부 위원은 최근 금융기관의 외화대출이 늘어나고 있는 것과 관련하 여 ...","['금융기관/NNG', '외화대출/NNG', '늘/VV', '금융기관/NNG', '..."
4,2005년도 제10차,2005-05-12,"', '또 다른 일부 위원은 전년 동기와 비교할 때 금년 1～4월중 국내시장에 대 ...","['또/MAG', '비교/NNG', '하/VV', '때/NNG', '중/NNG', ..."
...,...,...,...,...
10151,2017년도 제7차,2017-04-13,"', '외환시장의 효율성 제고를 위해서는 중장기적으로 원화를 국제화하고 경제주체들 ...","['외환시장/NNG', '효율성/NNG', '제고/NNG', '위하/VV', '중장..."
10152,2017년도 제7차,2017-04-13,"', '또한 동 위원은 비은행 가계대출이 증가세 관리와 같은 대응이 요구될 정도 의...","['비은행/NNG', '가계/NNG', '대출/NNG', '증가/NNG', '관리/..."
10153,2017년도 제7차,2017-04-13,"', '앞으로는 개별 기관별로도 파악해 볼 수 있도록 입수자료를 좀 더 미시 화하는...","['기관/NNG', '파악/NNG', '있/VV', '입수/NNG', '자료/NNG..."
10154,2017년도 제7차,2017-04-13,"', '이에 대해 관련부서에서는 작년에 은행의 여신심사 강화 등으로 가계대출수 요가...","['대해/VV', '은행/NNG', '여신/NNG', '심사/NNG', '강화/NN..."
10155,2017년도 제7차,2017-04-13,"', '아울러 동 위원은 우리나라의 수익률곡선이 다른 나라에 비해 평탄화되어 있 다...","['아울러/MAG', '일드커브/NNG', '나라/NNG', '비해/VV', '플래..."

In [7]:
#------------------------------n_gram split했을 때 이쁘게 뽑히게하기-----------------
for i in range(len(df_dic)):
    df_dic['n_gram'].iloc[i] = df_dic['n_gram'].iloc[i].replace("[","").replace("]","").replace("'","").replace(",","").split()

C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [8]:
df_dic['hawkish'] = np.zeros(len(df_dic))
df_dic['dovish'] = np.zeros(len(df_dic))

In [9]:
from tqdm.notebook import tqdm
for i in tqdm(range(len(df_dic))):
    haw_count = 0
    dov_count = 0 
    
    for word in df_dic['n_gram'][i]:
        if word in dic_dovish:
            dov_count += 1
        elif word in dic_hawkish:
            haw_count += 1
    df_dic['dovish'][i] = dov_count 
    df_dic['hawkish'][i] = haw_count

HBox(children=(FloatProgress(value=0.0, max=10156.0), HTML(value='')))

C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [10]:
df_dic[:5]

,ID,date,sent,n_gram,hawkish,dovish
0,2005년도 제10차,2005-05-12,['일부 위원은 내외금리차 역전에 따라 자금의 해외유출이 대규모로 발생될 가능성을 ...,"[내외/NNG, 금리갭/NNG, 역전/NNG, 자금/NNG, 해외/NNG, 유출/N...",1.0,6.0
1,2005년도 제10차,2005-05-12,"', '이에 대해 관련부서에서는 우리나라에서는 그러한 사례가 없었기 때문에 대만과 ...","[대해/VV, 그러/NNG, 사례/NNG, 없/VA, 사례/NNG, 살펴보/VV, ...",1.0,9.0
2,2005년도 제10차,2005-05-12,"', '동 위원은 자금의 해외유출에 대한 정책적 대응을 위해 내외금리나 환율에 대해...","[자금/NNG, 해외/NNG, 유출/NNG, 정책/NNG, 대응/NNG, 위하/VV...",0.0,5.0
3,2005년도 제10차,2005-05-12,"', '다른 일부 위원은 최근 금융기관의 외화대출이 늘어나고 있는 것과 관련하 여 ...","[금융기관/NNG, 외화대출/NNG, 늘/VV, 금융기관/NNG, 해외/NNG, 차...",0.0,2.0
4,2005년도 제10차,2005-05-12,"', '또 다른 일부 위원은 전년 동기와 비교할 때 금년 1～4월중 국내시장에 대 ...","[또/MAG, 비교/NNG, 하/VV, 때/NNG, 중/NNG, 시장/NNG, 대/...",0.0,8.0

In [11]:
df_dic['score_up'] = np.zeros(len(df_dic))

for i in range(len(df_dic)):
    score = (df_dic['hawkish'].iloc[i] - df_dic['dovish'].iloc[i]) / (df_dic['hawkish'].iloc[i] + df_dic['dovish'].iloc[i])
    if score > 0:
        df_dic['score_up'][i] = 1
    elif score < 0:
        df_dic['score_up'][i] = -1
    else:
        df_dic['score_up'][i] = 0
        
df_dic['score_down'] = np.zeros(len(df_dic))
for i in range(len(df_dic)):
    score = (df_dic['hawkish'].iloc[i] - df_dic['dovish'].iloc[i]) / (df_dic['hawkish'].iloc[i] + df_dic['dovish'].iloc[i])
    if score > 0:
        df_dic['score_down'][i] = 1
    elif score < 0:
        df_dic['score_down'][i] = 1
    else:
        df_dic['score_down'][i] = 0

C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in double_scalars
  after removing the cwd from sys.path.
C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in double_scalars

C:\Users\leeso\anaconda\envs\crawl\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [12]:
polarity = df_dic.groupby(df_dic['date']).sum()
polarity[:5]

            hawkish  dovish  score_up  score_down
date
2005-05-12    140.0   469.0    -103.0       133.0
2005-06-09    119.0   430.0    -101.0       129.0
2005-07-07    122.0   549.0    -120.0       134.0
2005-08-11    187.0   555.0     -93.0       139.0
2005-09-08    158.0   607.0    -102.0       130.0

In [13]:
#-----------------------------------0인값확인하기-------------------------------------
polarity[polarity['dovish'] == 0],polarity[polarity['hawkish'] == 0]

(Empty DataFrame
 Columns: [hawkish, dovish, score_up, score_down]
 Index: [],
 Empty DataFrame
 Columns: [hawkish, dovish, score_up, score_down]
 Index: [])

In [14]:
polarity['tone_doc'] = polarity['score_up'] / polarity['score_down']
polarity['tone_doc']

date
2005-05-12   -0.774436
2005-06-09   -0.782946
2005-07-07   -0.895522
2005-08-11   -0.669065
2005-09-08   -0.784615
                ...
2017-05-25   -1.000000
2017-07-13   -1.000000
2017-08-31   -1.000000
2017-10-19   -0.944444
2017-11-30   -0.937500
Name: tone_doc, Length: 124, dtype: float64

In [15]:
#---------------------------------기준금리 합치기---------------------------------------

In [16]:
base_rate = pd.read_csv('df_baserate.csv')
base_rate[:5]

           날짜  기준금리
0  2005-05-01  3.25
1  2005-05-02  3.25
2  2005-05-03  3.25
3  2005-05-04  3.25
4  2005-05-05  3.25

In [17]:
df_new = polarity.merge(base_rate, left_on='date', right_on='날짜', how='left')
df_new[:5]

   hawkish  dovish  score_up  score_down  tone_doc          날짜  기준금리
0    140.0   469.0    -103.0       133.0 -0.774436  2005-05-12  3.25
1    119.0   430.0    -101.0       129.0 -0.782946  2005-06-09  3.25
2    122.0   549.0    -120.0       134.0 -0.895522  2005-07-07  3.25
3    187.0   555.0     -93.0       139.0 -0.669065  2005-08-11  3.25
4    158.0   607.0    -102.0       130.0 -0.784615  2005-09-08  3.25

In [18]:
df_new.corr()

             hawkish    dovish  score_up  score_down  tone_doc      기준금리
hawkish     1.000000  0.799630 -0.715422    0.769202  0.763606  0.408791
dovish      0.799630  1.000000 -0.880843    0.873234  0.412632  0.182634
score_up   -0.715422 -0.880843  1.000000   -0.991833 -0.398860 -0.266945
score_down  0.769202  0.873234 -0.991833    1.000000  0.498220  0.305906
tone_doc    0.763606  0.412632 -0.398860    0.498220  1.000000  0.386033
기준금리        0.408791  0.182634 -0.266945    0.305906  0.386033  1.000000